version: "3"
services:
  web:
    build: "."
    depends_on:
      - mongo
    ports:
      - "8003:8003"
    volumes:
      - melissavolume:/var/lib/docker/volumes
    stdin_open: true
    tty: true
  mongo:
    image: mongo
    ports:
      - "27017:27017"
volumes:
  melissavolume:
